epics-gateways:
  # developer image for debugging no longer needed - defaults to helm chart version
  # image: ghcr.io/epics-containers/epics-gateways-developer:2026.3.18

  # use ixxdetector account for your beamline
  securityContext:
    # k8s-t11-beamline
    runAsUser: 36261
    runAsGroup: 36261

  hostNetwork: false
  baseIp: 10.43.0.0/16
